---
- name: test
  hosts: localhost
  tasks:
  - name: say hello to me
    shell: |
      pwd
      ls -alt
      echo "hello {{ name }}"
      register: foo
    debug: msg="the echo was {{ foo.stdout }}"

  
