---
- hosts: localhost
  connection: local
  tasks:
  - register: name
    shell: echo 'Hello {{ name }}'
     
  - register: ls
    shell: ls -alt
      
  - register: pwd
    shell: pwd
    
  - debug: msg="name: {{ name.stdout }}    ls: {{ ls.stdout }}  pwd: {{ pwd.stdout }}"
  
